# Generated by Django 6.1 on 2026-08-08 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('risk_level', models.CharField(default='LOW', max_length=20)),
                ('blockage_ratio', models.FloatField(default=0.0)),
                ('rainfall_last_hour_mm', models.FloatField(default=0.0)),
                ('humidity_pct', models.IntegerField(default=0)),
                ('temperature_c', models.FloatField(default=0.0)),
                ('dispatch_action', models.TextField(blank=True, default='')),
                ('last_inspection_date', models.DateField(blank=True, null=True)),
                ('last_cleaning_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('blockage_ratio', models.FloatField()),
                ('risk_level', models.CharField(max_length=20)),
                ('status', models.CharField(default='Pending Cleanup', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='processed_images/')),
                ('drain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='api.drain')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
